-voms=test.vo
-cert=assets/trust/test0.cert.pem
-key=assets/trust/test0.key.pem
-hostcert=assets/trust/star_test_example.cert.pem
-hostkey=assets/trust/star_test_example.key.pem
-certdir=assets/trust
-uri=voms.example:15000
-fqan="/test.vo"
-pastproxy=24:0
-hours=100
-pastac=24:0
-vomslife=12
