// SPDX-FileCopyrightText: 2025 Istituto Nazionale di Fisica Nucleare
//
// SPDX-License-Identifier: EUPL-1.2

const IAM_DASHBOARD_URL = process.env.IAM_DASHBOARD_URL;
const IAM_DASHBOARD_AUTH_SECRET = process.env.IAM_DASHBOARD_AUTH_SECRET ?? "";
const IAM_DASHBOARD_OIDC_CLIENT_ID = process.env.IAM_DASHBOARD_OIDC_CLIENT_ID!;
const IAM_DASHBOARD_OIDC_CLIENT_SECRET =
  process.env.IAM_DASHBOARD_OIDC_CLIENT_SECRET;
const IAM_DASHBOARD_OIDC_SCOPES = process.env.IAM_DASHBOARD_OIDC_SCOPES;
const IAM_API_URL = process.env.IAM_API_URL;

const url = new URL(IAM_DASHBOARD_URL!);
const IAM_DASHBOARD_BASE_PATH = url.pathname === "/" ? "" : url.pathname;

export const settings = {
  IAM_API_URL,
  IAM_DASHBOARD_URL,
  IAM_DASHBOARD_BASE_PATH,
  IAM_DASHBOARD_AUTH_SECRET,
  IAM_DASHBOARD_OIDC_CLIENT_ID,
  IAM_DASHBOARD_OIDC_CLIENT_SECRET,
  IAM_DASHBOARD_OIDC_SCOPES,
};
